### ISSUE TITLE
Is it possible to extract text data?

### ISSUE THREAD

**Issue by peterpme** [xaviervia/sketch2json#11]
Hey, awesome module!

I'm wondering if I can extract the values for the data (and if there's any reason to do so):

![image](https://user-images.githubusercontent.com/1211905/38886707-5b3f5598-423c-11e8-9a96-061e9b0b6f2e.png)

If I search the output for "Peter". I don't get anything back. Is this by design?

Thanks!

**Comment by xaviervia** [comment]
Hi!

That depends on the Sketch format, not on this tool in particular. It is possible that the text is coded in some way by Sketch, I haven't explored that myself. This tool does not deal with the specifics of the format other than by reading the ZIP file, so I do not hold this information :(
