### ISSUE TITLE
Suggestion: Include json operator for filter, enrich/decorate etc

### ISSUE THREAD

**Issue by kristianmandrup** [xaviervia/sketch2json#3]
Would be nice to integrate an efficient way to enrich or filter a Sketch json file, fx. using something like my [json-operator](https://www.npmjs.com/package/json-operator) or one of the alternatives...
What do you think?

**Comment by xaviervia** [comment]
Hm, sounds interesting. I'm not sure how the integration would look like,
I'm probably missing something, what would the benefit be of doing this as
part of sketch2json instead of consumers doing it on top?

**Comment by kristianmandrup** [comment]
You are right! I've added it to my wrapper ;) Much improved!
