### ISSUE TITLE
why start error  which Cannot find module 'folktale/data/task'

### ISSUE THREAD

**Issue by libaozhu87** [xaviervia/sketch2json#5]
![image](https://user-images.githubusercontent.com/4569022/27728663-5a3f8b52-5db5-11e7-9ab3-cd5e1729a775.png)

**Comment by libaozhu87** [comment]
need to fix  
![image](https://user-images.githubusercontent.com/4569022/27729629-27a4893c-5db9-11e7-87a4-007fb8605ca0.png)
change
![image](https://user-images.githubusercontent.com/4569022/27729655-35830e70-5db9-11e7-8d04-1051916b833b.png)

**Comment by xaviervia** [comment]
Fixed in https://github.com/xaviervia/sketch2json/releases/tag/v0.1.1 , thanks a lot for reporting!
